[package]
name = "schema_macro"
version = "0.1.0"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.53", features = ["full"] }

quote = "1.0.35"

proc-macro2 = "1.0.79"

serde = { version = "1.0.197", optional = true, features = ["derive"] }

[features]
default = ["serde"]
